version: '3.8'

services:
  nginx:
    env_file:
      - .env
    container_name : nginx
    build: requirements/nginx
    # image: nginx:latest
    volumes:
      - wp:/var/www/html # we specify which directory we need
    networks:
      - project
    ports:
      - "443:443"
    depends_on:
      - wordpress
    restart: always

  wordpress:
    env_file:
      - .env
    # environment:
      # - WORDPRESS_DB_NAME=${DB_NAME}
      # - WORDPRESS_TABLE_PREFIX=${WORDPRESS_TABLE_PREFIX:-wp_}
      # - WORDPRESS_DB_HOST=${DB_HOST:-mysql}
      # - WORDPRESS_DB_USER=${DB_USER:-root}
      # - WORDPRESS_DB_PASSWORD=${DB_PASSWORD:-password}=value
    container_name: wordpress
    build: requirements/wordpress
    # image: wordpress:latest
    volumes:
      - wp:/var/www/html/ #contains databases or other special files that programs often change.
    networks:
      - project
    depends_on:
    - mariadb
      # mariadb:
      #    condition: service_healthy
    restart: always
  
  mariadb:
    env_file:
      - .env
    container_name: mariadb
    build: requirements/mariadb
    volumes:
      - db:/var/lib/mysql # we specify which directory we need
    networks:
      - project
    restart: always
    # healthcheck:
    #   test: mysqladmin ping -u ${MYSQL_USER} --password=${MYSQL_PASSWORD}
    #   start_period: 5s
    #   interval: 5s
    #   timeout: 5s
    #   retries: 55

# Your volumes will be available in the /home/login/data folder of the
# host machine using Docker.
volumes:
  db:
    name: db
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/dselmy/data/database
  wp:
    name: wp
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/dselmy/data/wordpress

networks:
  project:
    name: inception_network
    driver: bridge
