version: '3.7'

services:
  nginx:
    env_file:
      - .env
    container_name : nginx
    build: requirements/nginx
    # image: nginx:latest
    volumes:
      - wp:/var/www/wordpress # we specify which directory we need
    networks:
      - project
    ports:
      - "443:443"
    depends_on:
      - wordpress
    restart: always

  wordpress:
    env_file:
      - .env
    environment:
      - WORDPRESS_DB_NAME=${DB_NAME}
      # - WORDPRESS_TABLE_PREFIX=${WORDPRESS_TABLE_PREFIX:-wp_}
      - WORDPRESS_DB_HOST=${DB_HOST:-mysql}
      - WORDPRESS_DB_USER=${DB_USER:-root}
      - WORDPRESS_DB_PASSWORD=${DB_PASSWORD:-password}=value
    container_name: wordpress
    build: requirements/wordpress
    # image: wordpress:latest
    volumes:
      - wp:/var/www/html/wordpress #contains databases or other special files that programs often change.
    networks:
      - project
    depends_on:
      - mariadb
    restart: always
  
  mariadb:
    # environment:
      # - MARIADB_ROOT_PASSWORD=root42
    env_file:
      - .env
    container_name: mariadb
    build: requirements/mariadb
    # image: mariadb:latest
    volumes:
      - db:/var/lib/mysql # we specify which directory we need
    networks:
      - project
    restart: always

# Your volumes will be available in the /home/login/data folder of the
# host machine using Docker.
volumes:
  db:
    name: db
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/dselmy/data/database
  wp:
    name: wp
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/dselmy/data/wordpress

networks:
  project:
    name: inception_network
    driver: bridge
